// Hub-owned thinking-effort (reasoning effort) library reader.
//
// Sources the per-model effort levels every endpoint's config面 and the relay's
// request面 injection both consume, so "which levels does this model speak" is
// answered in exactly one place.
//
// The library file is operator data, deliberately outside the repo:
//   %LOCALAPPDATA%\Anyswitch\thinking-efforts.db.json
// It is generated by the effort-library generator in the research workspace and
// hand-tuned through that generator's named rules, so editing it by hand is
// expected and reloads without a restart (cache key is mtimeMs + size).
//
// Resolution order for one model id:
//   1. library entry matched by canonical id (and its dot/dash spellings)
//   2. non-text library entry  -> no levels at all (never invent some)
//   3. optimistic default      -> high, xhigh, max (default high)
// Tier 3 is what makes a brand-new gateway model still adjustable: a missing row
// must not silently put the user back to "no thinking" — the cost of one ignored
// parameter is far below the cost of losing depth control on the newest model.
// The file's per-row `confidence` field ranks hand-review priority only; it must
// never gate whether levels are offered.
//
// Every entry point is fail-open by design (mirrors reasoning-fallback.mjs):
// a missing, unreadable or invalid library must degrade to the optimistic
// default, never break a model sync or a relay request.

import { existsSync, readFileSync, statSync } from "node:fs";
import { join } from "node:path";
import { relayDataRoot } from "./relay-settings.mjs";

const nodeFs = { existsSync, readFileSync, statSync };

const EFFORT_DB_FILENAME = "thinking-efforts.db.json";

// Library/level vocabulary, ordered from cheapest to deepest thinking.
// `light` sits between off and minimal: it is the lightest above-zero thinking
// some gateways offer (gpt-5.6+ speak light/medium/high/xhigh/max and no
// minimal/low at all). pi and DSH hard-validate against their own fixed level
// sets that predate it, so their endpoint vocabularies below deliberately
// exclude it — their pickers clip it away rather than break config load.
export const EFFORT_LEVELS_ORDER = Object.freeze([
  "off",
  "light",
  "minimal",
  "low",
  "medium",
  "high",
  "xhigh",
  "max",
]);

export const OPTIMISTIC_EFFORT_LEVELS = Object.freeze(["high", "xhigh", "max"]);
const OPTIMISTIC_EFFORT_DEFAULT = "high";

export function defaultEffortDbPath(base = process.env) {
  return join(relayDataRoot(base), EFFORT_DB_FILENAME);
}

/* ---------- model id canonicalization ---------- */

// Effort words a gateway folds into the model NAME ("claude-opus-4.7-max-thinking"
// is claude-opus-4.7 asked for one level). `flash`/`pro`/`lite`/`turbo`/`preview`
// are deliberately absent: those name a different model, stripping them would
// collapse distinct rows onto one entry.
const EFFORT_WORDS =
  "minimal|xlow|light|low|medium|med|high|xhigh|max|thinking|nothink|no-thinking|reasoner|reasoning|latest|free";
const EFFORT_TAIL_RE = new RegExp(`(?:-(${EFFORT_WORDS}))+$`, "i");

const NON_TEXT_RE = /embedding|diffusion|dall-e|stable-diffusion|sdxl|flux|whisper|tts|text-to-speech|speech|sensevoice|asr|kolors|meshy|agnes-(video|image)|video-\d|nano-banana|midjourney|minicpm.*audio|telespeech|imagegen|image-edit|image-|-image|imagine|bge-|reranker|\bocr\b|mineru|3d|texture|draft$|seedream|jimeng|kling|sora|veo-/i;

/**
 * Fold one gateway model id onto the library's key spelling.
 *
 * Order matters and is load-bearing: bracket prefixes are stripped in a loop
 * ("[次][AN]gemini-3.7-flash" is a relay-site decoration, not part of the id),
 * the effort tail is removed before the date tail (a dated id can carry both),
 * and the Claude "family name after version" reorder runs last so the earlier
 * steps see the raw spelling.
 */
export function canonicalizeModelId(rawId) {
  if (typeof rawId !== "string") return "";
  let s = rawId.trim();
  while (/^\[[^\]]*\]/.test(s)) s = s.replace(/^\[[^\]]*\]/, "").trim();
  s = s.replace(/\s+/g, "-");
  let c = s.toLowerCase().replace(/[\s_]+/g, "-");
  c = c.replace(EFFORT_TAIL_RE, "");
  c = c.replace(/-(\d{4})-?(\d{2})-?(\d{2})$/g, "").replace(/-(\d{4})(\d{2})(\d{2})$/g, "");
  c = c.replace(/-+$/g, "");
  // Namespace peel: "vendor/org/model" keeps the last segment as the model.
  while (c.includes("/")) {
    c = c.slice(c.indexOf("/") + 1);
  }
  const reordered = c.match(/^claude-(\d+)[.-](\d+)-(opus|sonnet|haiku)(.*)$/);
  if (reordered) {
    c = `claude-${reordered[3]}-${reordered[1]}-${reordered[2]}${reordered[4]}`;
  }
  return c;
}

/**
 * Candidate library keys for one model id, best match first.
 *
 * The dot/dash pair is not cosmetic: the generator folds "glm-5.3" and "glm-5-3"
 * into ONE row and re-keys it to whichever spelling appeared most often, so a
 * production id can legitimately canonicalize to a key the file does not hold.
 * Measured on the live store: 2 of 83 model ids resolve only through the fold.
 */
export function effortLookupKeys(rawId) {
  const canonical = canonicalizeModelId(rawId);
  const seeds = [canonical, typeof rawId === "string" ? rawId.trim().toLowerCase() : ""];
  const out = new Set();
  for (const seed of seeds) {
    if (!seed) continue;
    out.add(seed);
    out.add(seed.replace(/(\d)\.(\d)/g, "$1-$2"));
    out.add(seed.replace(/([a-z-]?)(\d+)-(\d+)(?=-|$)/, "$1$2.$3"));
    const reordered = seed.match(/^(claude|gemini|gpt)-(\d+)[.-](\d+)-([a-z]+)(.*)$/);
    if (reordered) {
      const [, family, major, minor, name, rest] = reordered;
      out.add(`${family}-${name}-${major}-${minor}${rest}`);
      out.add(`${family}-${name}-${major}.${minor}${rest}`);
    }
  }
  return [...out].filter(Boolean);
}

export function isNonTextModel(rawId) {
  return NON_TEXT_RE.test(rawId ?? "") || NON_TEXT_RE.test(canonicalizeModelId(rawId));
}

/* ---------- library load (hot reload, fail-open) ---------- */

/**
 * Keep only structurally sound rows. A bad row is skipped and counted rather
 * than voiding the whole table: one typo in a hand-tuned file must not cost
 * every model its levels.
 */
export function normalizeEffortEntry(entry) {
  if (entry === null || typeof entry !== "object" || Array.isArray(entry)) return null;
  const kind = entry.kind === "non-text" ? "non-text" : "reasoning";
  if (kind === "non-text") {
    return entry.levels === null || entry.levels === undefined
      ? { kind, levels: [], wire: {}, thinkingFormat: entry.thinkingFormat ?? null }
      : null;
  }
  if (!Array.isArray(entry.levels) || entry.levels.length === 0) return null;
  const levels = entry.levels.filter(
    (level, index, all) =>
      typeof level === "string" &&
      EFFORT_LEVELS_ORDER.includes(level) &&
      all.indexOf(level) === index,
  );
  if (levels.length === 0) return null;
  const declared = typeof entry.default === "string" && levels.includes(entry.default) ? entry.default : null;
  const wire = entry.wire && typeof entry.wire === "object" && !Array.isArray(entry.wire) ? entry.wire : {};
  return { kind, levels, default: declared, wire, thinkingFormat: entry.thinkingFormat ?? null };
}

/**
 * Read the library file. Returns `{ models, loadedCount, invalidCount, warning }`
 * where `warning` names why the file did not yield a usable table (missing /
 * unparseable / invalid schema) — callers log it, nothing throws.
 */
export function loadEffortCatalog(dbPath = defaultEffortDbPath(), io = {}) {
  const exists = io.existsSync ?? nodeFs.existsSync;
  const readFile = io.readFileSync ?? nodeFs.readFileSync;
  const stat = io.statSync ?? nodeFs.statSync;
  const empty = { models: new Map(), loadedCount: 0, invalidCount: 0, warning: null };
  if (!exists(dbPath)) return { ...empty, warning: "missing" };
  let text;
  try {
    text = readFile(dbPath, "utf8");
  } catch {
    return { ...empty, warning: "unreadable" };
  }
  let parsed;
  try {
    parsed = JSON.parse(text);
  } catch {
    return { ...empty, warning: "unparseable" };
  }
  const models = parsed?.models;
  if (models === null || typeof models !== "object" || Array.isArray(models)) {
    return { ...empty, warning: "invalid-schema" };
  }
  const table = new Map();
  let invalidCount = 0;
  for (const [key, raw] of Object.entries(models)) {
    const entry = normalizeEffortEntry(raw);
    if (!entry) {
      invalidCount += 1;
      continue;
    }
    table.set(key, entry);
  }
  return { models: table, loadedCount: table.size, invalidCount, warning: null, stat: safeStat(stat, dbPath) };
}

function safeStat(statFn, dbPath) {
  try {
    const stats = statFn(dbPath);
    return `${stats.mtimeMs}:${stats.size}`;
  } catch {
    return null;
  }
}

// One cached table per path, re-read when the file's mtime or size moves.
const catalogCache = new Map();

export function getEffortCatalog(dbPath = defaultEffortDbPath(), io = {}) {
  const key = `${dbPath}|${io.iomarker ?? "default"}`;
  const cached = catalogCache.get(key);
  const stamp = safeStat(io.statSync ?? nodeFs.statSync, dbPath);
  if (cached && cached.stamp === stamp) return cached.catalog;
  const catalog = loadEffortCatalog(dbPath, io);
  if (catalog.warning && cached) {
    // A hand-edit that breaks the file must cost the edit, not the levels:
    // keep serving the last usable table and pin this stamp, so the relay's
    // per-request lookup does not re-parse a broken file until it changes again.
    const degraded = { ...cached.catalog, warning: `${catalog.warning}-while-stale`, stale: true };
    catalogCache.set(key, { stamp, catalog: degraded });
    return degraded;
  }
  catalogCache.set(key, { stamp: catalog.stat ?? stamp, catalog });
  return catalog;
}

export function clearEffortCatalogCache() {
  catalogCache.clear();
}

// Every launcher's `sidecarRoot` argument IS the Anyswitch data root, which is
// where the library lives — one helper keeps the path derivation out of the
// six launchers that need it.
export function catalogForRoot(root, io = {}) {
  return getEffortCatalog(join(root, EFFORT_DB_FILENAME), io);
}

/* ---------- resolution ---------- */

/**
 * The effort levels one model offers, before any endpoint clips them.
 *
 * `origin` distinguishes a library row from the optimistic fallback so callers
 * (and tests) can tell them apart; it must never be used to decide whether to
 * offer levels at all.
 */
export function resolveModelEfforts(rawId, catalog = getEffortCatalog()) {
  const models = catalog?.models;
  if (models instanceof Map) {
    for (const key of effortLookupKeys(rawId)) {
      const entry = models.get(key);
      if (!entry) continue;
      return {
        levels: [...entry.levels],
        default: entry.default ?? pickDefaultEffort(entry.levels),
        wire: entry.wire ?? {},
        thinkingFormat: entry.thinkingFormat ?? null,
        kind: entry.kind,
        origin: "library",
        matchedKey: key,
      };
    }
  }
  if (isNonTextModel(rawId)) {
    return {
      levels: [], default: null, wire: {}, thinkingFormat: null,
      kind: "non-text", origin: "non-text", matchedKey: null,
    };
  }
  return {
    levels: [...OPTIMISTIC_EFFORT_LEVELS],
    default: OPTIMISTIC_EFFORT_DEFAULT,
    wire: {},
    thinkingFormat: null,
    kind: "reasoning",
    origin: "optimistic",
    matchedKey: null,
  };
}

// Deepest level the model offers that the operator did not rule out as a
// default; mirrors the generator's preference so config面 and request面 agree.
const DEFAULT_EFFORT_PREFERENCE = Object.freeze(["high", "xhigh", "medium", "max", "low", "minimal", "light"]);

export function pickDefaultEffort(levels) {
  const offered = (levels ?? []).filter((level) => level !== "off" && level !== "none");
  if (offered.length === 0) return null;
  return DEFAULT_EFFORT_PREFERENCE.find((level) => offered.includes(level))
    ?? offered[offered.length - 1];
}

/**
 * Wire spelling to send for one level. The library's `wire` is the raw
 * per-provider thinkingLevelMap (a superset of `levels`, `null` meaning
 * "supported but carries no value"), so a level routinely has no entry here —
 * the level name itself is then the value. That is what an OpenAI-shaped
 * upstream expects, and it keeps DSH's "non-off levels need a non-empty wire"
 * rule satisfiable.
 */
export function effortWireValue(resolved, level) {
  const wire = resolved?.wire?.[level];
  return typeof wire === "string" && wire.length > 0 ? wire : level;
}

/* ---------- per-endpoint vocabulary ---------- */

// Levels one endpoint will accept. `null` means the endpoint takes any string
// (it renders the list verbatim), so nothing is clipped.
const AGENT_EFFORT_VOCABULARIES = Object.freeze({
  dsh: Object.freeze(["off", "minimal", "low", "medium", "high", "xhigh", "max"]),
  pi: Object.freeze(["off", "minimal", "low", "medium", "high", "xhigh", "max"]),
  zcode: null,
  kimi: null,
  qoder: Object.freeze([]),
});

export function intersectEffortVocabulary(levels, agent) {
  const vocabulary = AGENT_EFFORT_VOCABULARIES[agent];
  if (vocabulary === undefined || vocabulary === null) return [...levels ?? []];
  return EFFORT_LEVELS_ORDER.filter((level) => levels?.includes(level) && vocabulary.includes(level));
}

// Reasonix validates an effort against its channel family's accepted set and
// hard-errors on anything else, so levels are intersected with the family set
// before writing. An unknown family is unrestricted (write what the library
// says); an intersection that comes back empty means the caller skips the model
// entirely — "not written" keeps the endpoint as it is, "written wrong" breaks it.
const REASONIX_FAMILY_ALLOW_SETS = [
  { re: /deepseek/i, allow: Object.freeze(["low", "high", "max", "disabled"]) },
  { re: /longcat/i, allow: Object.freeze(["enabled", "disabled"]) },
  { re: /minimax/i, allow: Object.freeze(["adaptive", "disabled"]) },
];

export function intersectReasonixEfforts(levels, modelId) {
  const family = REASONIX_FAMILY_ALLOW_SETS.find((rule) => rule.re.test(modelId ?? ""));
  if (!family) return [...levels ?? []];
  return (levels ?? []).filter((level) => family.allow.includes(level));
}

/**
 * What one endpoint should be told about one model's thinking depth, already
 * clipped to what that endpoint can render.
 *
 * Returns null when there is nothing worth writing — a non-text model, or a
 * vocabulary/family intersection that came back empty. Writers must then leave
 * the model alone: an absent declaration keeps the endpoint working exactly as
 * it did before, a wrong one can hard-fail its config load.
 */
export function modelEffortSurface(rawId, { catalog, agent } = {}) {
  const resolved = resolveModelEfforts(rawId, catalog);
  if (resolved.kind === "non-text" || resolved.levels.length === 0) return null;
  const levels = agent === "reasonix"
    ? intersectReasonixEfforts(resolved.levels, rawId)
    : intersectEffortVocabulary(resolved.levels, agent);
  if (levels.length === 0) return null;
  const level = levels.includes(resolved.default) ? resolved.default : pickDefaultEffort(levels);
  if (!level) return null;
  return {
    levels,
    default: level,
    wire: resolved.wire,
    thinkingFormat: resolved.thinkingFormat,
    origin: resolved.origin,
  };
}
